class EventsPageElements:
    new_events_button = "text = New event"
    event_name = "[placeholder=\"Caption\"]"
    date = "[placeholder=\"Pick a date\"]"
    time_hh = "input[name=\"time_h\"]"
    time_mm = "[placeholder=\"mm\"]"
    next_button = "text = Next"
    create_button = "button:has-text(\"Create\")"
    event_created_success_message = "text=Event successfully created"
    private_event_radio_button = "text=Private event"
