class ConferencePage:
    new_conference_button = "text = New Conference >> nth =1"
    create_conf_popup_room_selector = "text=*Choose a conference room Choose a room for the conference to take place. The ro >> select"
    conference_name = "input[name=\"meeting-name\"]"
    date = "[placeholder=\"Pick a date\"]"
    hh = "[placeholder = HH]"
    mm = "[placeholder = MM]"
    next_button = "button:has-text(\"Next\")"
    create_button = "button:has-text(\"Create\")"
    cross_on_conference_help_popup = ".absolute.inset-x-0 .button >> nth = 1"
    conference_rooms_tab = "text=Conference rooms"
    standard_conf_room = "text=Standard conference room >> nth=2"
    standard_conf_room_new_conf_button = "text=Create web conference"
    conference_creation_success_message = "text=The web conference successfully created"
    closed_conference_radio_button = "text = Closed conference"
