class GroupsTab:
    new_group_button = "button:has-text(\"New Group\")"
    group_type_public_radio_button = "text=Group Type Public group Visible in search and under interests. Anyone can join C >> button"
    group_name_caption_field = "[placeholder=\"Caption\"]"
    group_description = "textarea[name=\"description\"]"
    group_keyword = "[placeholder=\"Add keywords to make the group easier to find\"]"
    group_create_button = "button:has-text(\"Create\")"
    group_create_popup_next_button = "button:has-text(\"Next\")"
    # group_created_confirmation_popup_open_button = "button:has-text(\"Open\") >> nth =1"
    # group_creation_popup_closed_radio_button = "text=Group Type Public group Visible in search and under interests. Anyone can join C >> button >> nth=1"
    group_creation_popup_closed_radio_button = "text = Closed group"
    group_creation_popup_private_radio_button = "text = Private group"
    group_created_successfully_popup_open_button = "text = Open"
